const express = require('express');
const bodyParser = require('body-parser');
const router = express.Router();

const uuidv4 = require('uuid/v4');
const nodemailer = require('nodemailer');
const credentials = require('../adminSecrets');
const fs = require('fs');
const os = require('os');

var imageDirectory = os.homedir() + "/Images/";
!fs.existsSync(imageDirectory) && fs.mkdirSync(imageDirectory);

const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: credentials.GMAIL_ACCOUNT,
        pass: credentials.GMAIL_PASSWORD
    }
});

const mailOptions = {
    from: credentials.GMAIL_ACCOUNT,
    to: null,
    subject: null,
    text: null
};

// string generated by canvas.toDataURL()
// var img = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0"
//     + "NAAAAKElEQVQ4jWNgYGD4Twzu6FhFFGYYNXDUwGFpIAk2E4dHDRw1cDgaCAASFOffhEIO"
//     + "3gAAAABJRU5ErkJggg==";

// adapted from https://gist.github.com/madhums/e749dca107e26d72b64d
function saveImage(img, outputName) {
    // strip off the data: url prefix to get just the base64-encoded bytes
    var data = img.replace(/^data:image\/\w+;base64,/, "");
    var buf = new Buffer(data, 'base64');
    fs.writeFile(outputName + ".png", buf, function(err) { 
        if (err) throw err;
        console.log("Saved!");
    });
}

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index');
});

// Route: Show *all* wisps
// example url: domain.com/api/wisps?lat=45.01&long=123.40&d=5.0&ts=1245073530000
// return template 
// [{"id":"UUIDv4","title":"wisp title","loc":{"lon":0,"lat":0}}, {...}, {...}]
router.get('/api/wisps', function(req, res) {
    var db = req.db;
    var collection = db.get('whatsThatWeirdThing');

    var lat = req.query.lat;
    var long = req.query.long;
    var dist = req.query.d;
    var deltatime = req.query.ts ? parseInt(req.query.ts) : 0;

    collection.find({"creation_date": {"$gte": deltatime}},{},function(error, docs) {
        if (error) {
            res.ststus(500).json();
        } else {
            var wispLocations = [];
            for (var i = 0; i < docs.length; i++) {
                wispLocations[i] = {"id": docs[i].id, "title": docs[i].title, "loc": docs[i].loc}
            }
            res.status(200).json(wispLocations);
        }
    });     
});

// WISP template
// {"id":"UUIDv4","title":"wisp title","description":"desc of what was seen",
//  "email":"user@wot.com","loc":{"lon":0,"lat":0},"photos":["file/path/of/photo1"],
//  "responses":["response1","response2","..."],"creation_date":"UNIX timestamp"}

// Route: get wisps by email
router.get('/api/wisps/:email', function(req, res){
    var collection = req.db.get('whatsThatWeirdThing');
    var email = req.params.email;

    collection.find({"email": email},{}, function(error, wispsByEmail) {
        if (error) {
            res.ststus(500).json(); 
        } else {
            if (wispsByEmail != null) {
                for (var i = 0; i < wispsByEmail.length; i++) {
                    delete wispsByEmail[i]._id;
                }
                res.status(200).json(wispsByEmail);
            } else {
                res.status(404).json();
            }
        }
    });
});

// Route: get wisp by id
router.get('/api/wisp/:id', function(req, res){
    var collection = req.db.get('whatsThatWeirdThing');

    var id = req.params.id;
    collection.findOne({"id": id},{}, function(error, doc) {
        if (error) {
            res.ststus(500).json(); 
        } else {
            if (doc != null) {
                delete doc._id
                res.status(200).json(doc);
            } else {
                res.status(404).json();
            }
        }
    });
});

// Route: Create a wisp
router.post('/api/wisps', function(req, res) {
    var collection = req.db.get('whatsThatWeirdThing');

    if ((!req.body.title && !req.body.description) || !req.body.email || req.body.lon == null || req.body.lat == null) {
        res.status(400).json();
        return;
    }

    var id = uuidv4();
    var photoPath = "";
    if (req.body.image) {
        saveImage(req.body.image, id);
        photoPath = imageDirectory + id + ".png"; 
    }
    var new_wisp = {"id": id, "title": req.body.title, "description": req.body.description, 
                    "loc":{"lon": req.body.lon, "lat": req.body.lat}, "email": req.body.email,
                    "photos":[photoPath], "responses":[], "creation_date": new Date().getTime()};

    collection.insert(new_wisp, function (error, doc) {
        if (error) {
            res.ststus(500).json();
        } else {
            res.status(200).json(new_wisp);
        }
    });
});

// Route: Respond to a wisp
router.post('/api/wisp/:id', function(req, res) {
    var collection = req.db.get('whatsThatWeirdThing');
    var id = req.params.id;

    if (!req.body.message) {
        res.status(400).json();
        return;
    }

    collection.findOne({"id": id},{}, function(error, doc) {
        if (error) {
            res.ststus(500).json();
        } else {
            if (doc.responses.length == 0) {
                mailOptions.text = "Greetings User,\nSomeone has responded to your request for information about " + doc.title + ". Go to your list of WISPs in What's That to see the response.\n-The What's That Team";
                mailOptions.to = doc.email;
                mailOptions.subject = "Your pin " + doc.title + " was just responded to for the first time!";
                if (mailOptions.to && mailOptions.text) {
                    transporter.sendMail(mailOptions, function(error, info) {
                        if (error) {
                            console.log(error);
                        } else {
                            console.log('Email sent: ' + info.response);
                        }
                    });
                }
            } 

            doc.responses.push(req.body.message);
            collection.update({"id": doc.id}, {$set: {"responses": doc.responses}}, function(error, count, status) {
                if (error) {
                    res.ststus(500).json();
                } else {
                    console.log("WISP " + doc.id + "responsed to! " + count + " " + status);
                    delete doc._id; 
                    res.status(200).json(doc);
                }
            });
        }
    });
});

// Route: Delete a wisp
router.delete('/api/wisp/:id', function(req, res) {
    var collection = req.db.get('whatsThatWeirdThing');
    var id = req.params.id;

    collection.delete({"id": id}, function(error, doc) {
        if (error) {
            res.ststus(500).json();
        } else {
            res.status(200).json();
        }
    });
});

module.exports = router;


